### ISSUE TITLE
Error when using plugin with Material for MkDocs

### ISSUE THREAD

**Issue by zeldridge** [prcr/mkdocs-meta-descriptions-plugin#186]
Hi,
I get this error when trying to use the plugin with Material for MkDocs. What am I doing wrong?

![image](https://user-images.githubusercontent.com/71633378/186575375-8e66a0e1-d291-4b7e-af5c-0c04066c555a.png)

**Comment by prcr** [comment]
Hello @zeldridge,

I'll have a closer look later today, but in the meanwhile, could you provide a few more details to help me reproduce the issue?

Please let me know:

- The contents of your `mkdocs.yml` file (or at least the `markdown_extensions` and `plugins` configurations)
- Which version of MkDocs Material are you using? Are you using the [Insiders version](https://squidfunk.github.io/mkdocs-material/insiders/)?
- Do you get any errors when you run `mkdocs build`?

**Comment by prcr** [comment]
I was finally able to reproduce the error that you came across.

As far as I could understand, you're using [MkDocs Material theme's `schema.json` file](https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration) to validate your `mkdocs.yml` file. However, this schema only accepts the built-in plugins of the Material theme [and a few others](https://github.com/squidfunk/mkdocs-material/blob/42aaa2146205f42d6ad6e07e8bad66422503bff1/docs/schema/plugins.json#L45-L84).

You can safely ignore the error for now, as long as your site builds correctly when you run `mkdocs build`.

I'll leave this issue open, as I should be able to create a `schema.json` file for this plugin and then ask the MkDocs Material maintainer to include it in their schema, which will make the validation error disappear.
